## Tasks

1. Read CSV

2. Show first 5 rows

3. Check missing values in each column   (Hint: isnull())

4. Count total missing values in the entire dataset

5. Show only rows having missing values

6. Fill missing Salary values with average salary

This is a super important real-world task.

Average Salary=                ∑Salary
                      Number of non-missing salaries


7. Fill missing City values with "Unknown"

8. Drop rows where Department is missing   (This simulates removing bad/incomplete records.)

9. Find average salary department-wise

In [13]:
# 1. Read CSV

import pandas as pd

df = pd.read_csv('employee_data.csv')

In [14]:
# 2. Show first 5 rows

df.head()

   Employee_ID   Name Department   Salary  Experience       City
0          201   Aman         IT  55000.0         3.0  Bangalore
1          202   Sana         HR      NaN         5.0  Hyderabad
2          203  Rohit         IT  62000.0         NaN      Delhi
3          204   Zara    Finance  58000.0         4.0        NaN
4          205  Arjun         IT  60000.0         2.0  Bangalore

In [15]:
# 3. Check missing values in each column

df.isna().sum()

Employee_ID    0
Name           0
Department     1
Salary         2
Experience     2
City           1
dtype: int64

In [16]:
# 4. Count total missing values in the entire dataset

df.isna().sum().sum()

np.int64(6)

In [20]:
# 5. Show only rows having missing values

df[df.isna().any(axis=1)]

   Employee_ID    Name Department   Salary  Experience       City
1          202    Sana         HR      NaN         5.0  Hyderabad
2          203   Rohit         IT  62000.0         NaN      Delhi
3          204    Zara    Finance  58000.0         4.0        NaN
6          207   Karan        NaN  49000.0         1.0      Delhi
7          208  Fatima    Finance      NaN         6.0     Mumbai
9          210   Ahmed         HR  53000.0         NaN  Hyderabad

In [ ]:
# 6. Fill missing Salary values with average salary

df['Salary']=df['Salary'].fillna(df['Salary'].median())
df

   Employee_ID    Name Department   Salary  Experience       City
0          201    Aman         IT  55000.0         3.0  Bangalore
1          202    Sana         HR  56500.0         5.0  Hyderabad
2          203   Rohit         IT  62000.0         NaN      Delhi
3          204    Zara    Finance  58000.0         4.0        NaN
4          205   Arjun         IT  60000.0         2.0  Bangalore
5          206   Meera         HR  52000.0         3.0    Chennai
6          207   Karan        NaN  49000.0         1.0      Delhi
7          208  Fatima    Finance  56500.0         6.0     Mumbai
8          209    Riya         IT  61000.0         4.0  Bangalore
9          210   Ahmed         HR  53000.0         NaN  Hyderabad

In [ ]:
# 7. Fill missing City values with "Unknown"

df['City'] = df['City'].fillna('Unknown')
df

   Employee_ID    Name Department   Salary  Experience       City
0          201    Aman         IT  55000.0         3.0  Bangalore
1          202    Sana         HR  56500.0         5.0  Hyderabad
2          203   Rohit         IT  62000.0         NaN      Delhi
3          204    Zara    Finance  58000.0         4.0    Unknown
4          205   Arjun         IT  60000.0         2.0  Bangalore
5          206   Meera         HR  52000.0         3.0    Chennai
6          207   Karan        NaN  49000.0         1.0      Delhi
7          208  Fatima    Finance  56500.0         6.0     Mumbai
8          209    Riya         IT  61000.0         4.0  Bangalore
9          210   Ahmed         HR  53000.0         NaN  Hyderabad

In [22]:
# 8. Drop rows where Department is missing   (This simulates removing bad/incomplete records.)

df=df.dropna(subset=['Department'])
df

   Employee_ID    Name Department   Salary  Experience       City
0          201    Aman         IT  55000.0         3.0  Bangalore
1          202    Sana         HR      NaN         5.0  Hyderabad
2          203   Rohit         IT  62000.0         NaN      Delhi
3          204    Zara    Finance  58000.0         4.0        NaN
4          205   Arjun         IT  60000.0         2.0  Bangalore
5          206   Meera         HR  52000.0         3.0    Chennai
7          208  Fatima    Finance      NaN         6.0     Mumbai
8          209    Riya         IT  61000.0         4.0  Bangalore
9          210   Ahmed         HR  53000.0         NaN  Hyderabad

In [ ]:
# 9. Find average salary department-wise

df.groupby('Department')['Salary'].mean()

Department
Finance    57250.000000
HR         53833.333333
IT         59500.000000
Name: Salary, dtype: float64