#  Mastering Pandas for Placements: Zero to Advanced Beginner

##### Welcome to this interactive, fully-structured guide! Pandas is the most crucial library for data manipulation in Python. Whether you're aiming for a Data Scientist, Analyst, or Software Engineering role, mastering Pandas is essential.

### Note:
##### As this is posted on github by me, this is open source, You can download this and use this cz this notebook is made for you with intentional empty code blocks, and there is another notebook named practice, you can go through that too may me u might find something new and interesting. Happy learning !! 

##  What to expect:
- **Theory**: Simple, straight-to-the-point explanations.
- **Code**: Real-world, placement-focused examples.
- **Tasks**: Mini-challenges after every topic to test your understanding.

Let's import the libraries and begin!

In [2]:
import pandas as pd
import numpy as np     # this is just another library in python which u can explore 

# something u need to know : Pandas is built on top of NumPy and uses NumPy’s data structures and operations internally.

print("✅ Pandas and NumPy imported successfully!")
print(f"Pandas version: {pd.__version__}")

✅ Pandas and NumPy imported successfully!
Pandas version: 2.3.3

### There are 2 datatypes in Pandas
1. Series
2. DataFrame

## 1.  Series
**Theory:** A `Series` is a one-dimensional array-like object capable of holding any data type (integers, strings, floats, Python objects, etc.). Think of it as a single column in an Excel sheet.

**Scenario:** We are tracking the interview scores of 5 candidates.

In [3]:
# Creating a Series from a list
scores = [85, 92, 78, 90, 88]
candidates = ['Aarav', 'Priya', 'Rohan', 'Sneha', 'Vikram']

score_series = pd.Series(data=scores, index=candidates, name="Interview_Scores")
print(score_series)

Aarav     85
Priya     92
Rohan     78
Sneha     90
Vikram    88
Name: Interview_Scores, dtype: int64

**🛠️ Practice Task 1:** 
Create a Pandas Series storing the number of coding problems solved by 4 of your friends. Use their names as the index.

In [4]:
# [Write your code here]

## 2.  DataFrame
**Theory:** A `DataFrame` is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table. It is the most commonly used pandas object.

In [5]:
# Creating an empty DataFrame and checking its type
empty_df = pd.DataFrame()
print(type(empty_df))

<class 'pandas.core.frame.DataFrame'>

## 3.  Creating DataFrames
**Theory:** You can create DataFrames from dictionaries, lists of lists, or even Series. Let's create a dataset of candidates applying for a Tech role.

In [6]:
# Creating a DataFrame from a dictionary
data = {
    'Candidate_ID': ['C001', 'C002', 'C003', 'C004', 'C005'],
    'Name': ['Ayla', 'Ben', 'Chloe', 'Dan', 'Eva'],
    'Python_Score': [90, 75, 88, 60, 95],
    'SQL_Score': [85, 80, 92, 70, 88],
    'Outcome': ['Selected', 'Rejected', 'Selected', 'Rejected', 'Selected']
}

df_candidates = pd.DataFrame(data)
display(df_candidates)

  Candidate_ID   Name  Python_Score  SQL_Score   Outcome
0         C001   Ayla            90         85  Selected
1         C002    Ben            75         80  Rejected
2         C003  Chloe            88         92  Selected
3         C004    Dan            60         70  Rejected
4         C005    Eva            95         88  Selected

**🛠️ Practice Task 2:**
Create a DataFrame containing 3 columns: `Project_Name`, `Tech_Stack`, and `Completion_Status` for any 3 projects.

In [7]:
# [Write your code here]

## 4.  Reading & Exporting CSV
**Theory:** In real-world scenarios, we read data from CSV, Excel, or SQL databases. Let's generate a temporary CSV file with fake employee data to simulate a real workflow.

In [8]:
# Creating dummy employee data for the rest of our tutorial
employee_data = {
    'Emp_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Name': ['Sam', 'Nina', 'Leo', 'Mia', 'Jay', 'Zoe', 'Tom', 'Sam'],
    'Department': ['Data', 'Engineering', 'Data', 'HR', 'Engineering', 'Marketing', 'Data', 'Data'],
    'Salary': [75000, 90000, 82000, 60000, 95000, 65000, 78000, 75000],
    'Experience_Years': [2, 5, 3, 1, 6, 2, 3, 2],
    'Joining_Date': ['2021-05-10', '2019-03-15', '2020-08-20', '2023-01-10', '2018-11-05', '2022-07-01', '2020-12-01', '2021-05-10']
}

temp_df = pd.DataFrame(employee_data)

# Exporting to CSV (Topic: Exporting CSV)
temp_df.to_csv('company_employees.csv', index=False)
print("File 'company_employees.csv' created successfully!")

# Reading the CSV
df = pd.read_csv('company_employees.csv')
print("File read successfully! First 2 rows:")
display(df.head(2))

File 'company_employees.csv' created successfully!
File read successfully! First 2 rows:

   Emp_ID  Name   Department  Salary  Experience_Years Joining_Date
0     101   Sam         Data   75000                 2   2021-05-10
1     102  Nina  Engineering   90000                 5   2019-03-15

**🛠️ Practice Task 3:**
Read the CSV file again, but load only the first 3 rows using a parameter inside `read_csv`. *(Hint: use `nrows`)*

In [9]:
# [Write your code here]

## 5.  Data Inspection: head, tail, shape, columns, info, describe
**Theory:** Once data is loaded, you must inspect it to understand its shape, data types, and statistical properties.
- `head(n)` / `tail(n)`: Top / Bottom `n` rows.
- `shape`: Tuple of (rows, columns).
- `columns`: List of column names.
- `info()`: Column data types and non-null counts.
- `describe()`: Mathematical summary of numerical columns.

In [10]:
print("--- SHAPE ---")
print(df.shape)
print()

print("\n--- COLUMNS ---")
print(df.columns.tolist())
print()

print("\n--- HEAD (Top 3) ---")
display(df.head(3))
print()

print("\n--- TAIL (Bottom 2) ---")
display(df.tail(2))
print()

print("\n--- INFO ---")
df.info()
print()

print("\n--- DESCRIBE ---")
display(df.describe())

--- SHAPE ---
(8, 6)


--- COLUMNS ---
['Emp_ID', 'Name', 'Department', 'Salary', 'Experience_Years', 'Joining_Date']


--- HEAD (Top 3) ---

   Emp_ID  Name   Department  Salary  Experience_Years Joining_Date
0     101   Sam         Data   75000                 2   2021-05-10
1     102  Nina  Engineering   90000                 5   2019-03-15
2     103   Leo         Data   82000                 3   2020-08-20

--- TAIL (Bottom 2) ---

   Emp_ID Name Department  Salary  Experience_Years Joining_Date
6     107  Tom       Data   78000                 3   2020-12-01
7     108  Sam       Data   75000                 2   2021-05-10

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Emp_ID            8 non-null      int64
 1   Name              8 non-null      object
 2   Department        8 non-null      object
 3   Salary            8 non-null      int64
 4   Experience_Years  8 non-null      int64
 5   Joining_Date      8 non-null      object
dtypes: int64(3), object(3)
memory usage: 516.0+ bytes


--- DESCRIBE ---

          Emp_ID        Salary  Experience_Years
count    8.00000      8.000000          8.000000
mean   104.50000  77500.000000          3.000000
std      2.44949  11698.595764          1.690309
min    101.00000  60000.000000          1.000000
25%    102.75000  72500.000000          2.000000
50%    104.50000  76500.000000          2.500000
75%    106.25000  84000.000000          3.500000
max    108.00000  95000.000000          6.000000

**🛠️ Practice Task 4:**
Display the statistical summary (`describe`) but only for the `Experience_Years` column.

In [10]:
# [Write your code here]

## 6.  Column Indexing & Slicing
**Theory:** Selecting single or multiple columns.
- Single column: `df['ColumnName']` (returns a Series).
- Multiple columns: `df[['Col1', 'Col2']]` (returns a DataFrame).

In [11]:
# Single Column (Series)
departments = df['Department']
print("Type of single column:", type(departments))
display(departments.head(2))

# Multiple Columns (DataFrame)
subset = df[['Name', 'Salary']]
print("\nType of multiple columns:", type(subset))
display(subset.head(2))

Type of single column: <class 'pandas.core.series.Series'>

0           Data
1    Engineering
Name: Department, dtype: object

Type of multiple columns: <class 'pandas.core.frame.DataFrame'>

   Name  Salary
0   Sam   75000
1  Nina   90000

**🛠️ Practice Task 5:**
Select and display only the `Emp_ID` and `Experience_Years` columns.

In [12]:
# [Write your code here]

## 7.  Row & Column Selection: loc and iloc
**Theory:** 
- `loc[]`: Label-based indexing (select rows/cols by their labels/names).
- `iloc[]`: Integer-based indexing (select rows/cols by their integer positions).

In [13]:
# Setting 'Emp_ID' as index momentarily to demonstrate .loc
df_indexed = df.set_index('Emp_ID')

# .loc example: Select employee with ID 103's Name and Salary
print("Using loc:")
display(df_indexed.loc[103, ['Name', 'Salary']])

# .iloc example: Select 1st to 3rd row, and 1st to 2nd column
print("\nUsing iloc (First 3 rows, First 2 columns):")
display(df.iloc[0:3, 0:2])

Using loc:

Name        Leo
Salary    82000
Name: 103, dtype: object

Using iloc (First 3 rows, First 2 columns):

   Emp_ID  Name
0     101   Sam
1     102  Nina
2     103   Leo

**🛠️ Practice Task 6:**
Using `iloc`, select the last 2 rows and the last 3 columns of `df`.

In [14]:
# [Write your code here]

## 8.  Filtering Data
**Theory:** Filtering allows extracting subsets of data based on specific conditions.

In [15]:
# Condition 1: Employees with Salary > 80000
high_salary = df[df['Salary'] > 80000]
print("--- High Salary Employees ---")
display(high_salary)

# Condition 2: Data Department employees with > 2 years experience
data_seniors = df[(df['Department'] == 'Data') & (df['Experience_Years'] > 2)]
print("\n--- Senior Data Employees ---")
display(data_seniors)

--- High Salary Employees ---

   Emp_ID  Name   Department  Salary  Experience_Years Joining_Date
1     102  Nina  Engineering   90000                 5   2019-03-15
2     103   Leo         Data   82000                 3   2020-08-20
4     105   Jay  Engineering   95000                 6   2018-11-05

--- Senior Data Employees ---

   Emp_ID Name Department  Salary  Experience_Years Joining_Date
2     103  Leo       Data   82000                 3   2020-08-20
6     107  Tom       Data   78000                 3   2020-12-01

**🛠️ Practice Task 7:**
Filter the DataFrame to show employees from the 'Engineering' department who earn less than 95000.

In [16]:
# [Write your code here]

## 9.  Sorting Data
**Theory:** Use `.sort_values()` to arrange data in ascending or descending order.

In [17]:
# Sort by Salary descending, then by Experience ascending
df_sorted = df.sort_values(by=['Salary', 'Experience_Years'], ascending=[False, True])
display(df_sorted.head(4))

   Emp_ID  Name   Department  Salary  Experience_Years Joining_Date
4     105   Jay  Engineering   95000                 6   2018-11-05
1     102  Nina  Engineering   90000                 5   2019-03-15
2     103   Leo         Data   82000                 3   2020-08-20
6     107   Tom         Data   78000                 3   2020-12-01

**🛠️ Practice Task 8:**
Sort `df` alphabetically by 'Name' from Z to A.

In [18]:
# [Write your code here]

## 10.  Handling Missing Values (fillna, dropna)
**Theory:** Real data is messy and often contains `NaN` (Not a Number) values.
- `dropna()`: Remove rows or columns containing missing values.
- `fillna()`: Replace missing values with specific data (e.g., mean, median, or fixed value).

In [19]:
# Creating a dummy DataFrame with missing values
missing_data = pd.DataFrame({
    'Student': ['Alice', 'Bob', 'Charlie', 'David'],
    'Score': [85, np.nan, 90, np.nan],
    'Status': ['Pass', 'Fail', np.nan, 'Pass']
})
print("Original Missing Data:")
display(missing_data)

# dropna(): drop rows with ANY missing value
print("\nAfter dropna():")
display(missing_data.dropna())

# fillna(): fill Score with mean score, Status with 'Unknown'
print("\nAfter fillna():")
missing_data['Score'] = missing_data['Score'].fillna(missing_data['Score'].mean())
missing_data['Status'] = missing_data['Status'].fillna('Unknown')
display(missing_data)

Original Missing Data:

   Student  Score Status
0    Alice   85.0   Pass
1      Bob    NaN   Fail
2  Charlie   90.0    NaN
3    David    NaN   Pass

After dropna():

  Student  Score Status
0   Alice   85.0   Pass

After fillna():

   Student  Score   Status
0    Alice   85.0     Pass
1      Bob   87.5     Fail
2  Charlie   90.0  Unknown
3    David   87.5     Pass

**🛠️ Practice Task 9:**
Create a pandas Series with values `[10, np.nan, 30, np.nan]`. Add code to fill the missing values with the number `0`.

In [20]:
# [Write your code here]

## 11.  Duplicates
**Theory:** Sometimes duplicate rows exist in a dataset. Use `duplicated()` to identify them and `drop_duplicates()` to remove them.

In [22]:
df = pd.read_csv('company_employees.csv') # note: to show this topic I manually added a duplicate value in the dataset and removed it later

In [ ]:
print("Total rows before dropping duplicates:", len(df))

# Check for duplicates
print("\nDuplicated rows:")
display(df[df.duplicated()])

# Drop duplicates (assign to a new DataFrame or use inplace=True)
df_clean = df.drop_duplicates()
print("\nTotal rows after dropping duplicates:", len(df_clean))

# when no duplicate values exist the DataFrame comes empty

Total rows before dropping duplicates: 9

Duplicated rows:

   Emp_ID Name Department  Salary  Experience_Years Joining_Date
1     101  Sam       Data   75000                 2   2021-05-10

Total rows after dropping duplicates: 8

**🛠️ Practice Task 10:**
Looking at the documentation for `drop_duplicates()`, find out how to keep the *last* occurrence of a duplicate instead of the first. Write the syntax below.

In [22]:
# [Write your code here]

## 12.  String Operations
**Theory:** Pandas provides the `.str` accessor to apply string functions (like upper, lower, contains, replace) element-wise on a column.

In [23]:
# 1. Convert Names to Uppercase
df_clean['Name_Upper'] = df_clean['Name'].str.upper()

# 2. Check if Department contains the word 'Data'
df_clean['Is_Data_Role'] = df_clean['Department'].str.contains('Data')

# 3. Replace 'Engineering' with 'Engg'
df_clean['Short_Dept'] = df_clean['Department'].str.replace('Engineering', 'Engg')

display(df_clean[['Name', 'Name_Upper', 'Department', 'Short_Dept', 'Is_Data_Role']])

   Name Name_Upper   Department Short_Dept  Is_Data_Role
0   Sam        SAM         Data       Data          True
1  Nina       NINA  Engineering       Engg         False
2   Leo        LEO         Data       Data          True
3   Mia        MIA           HR         HR         False
4   Jay        JAY  Engineering       Engg         False
5   Zoe        ZOE    Marketing  Marketing         False
6   Tom        TOM         Data       Data          True
7   Sam        SAM         Data       Data          True

**🛠️ Practice Task 11:**
Create a new column called 'Name_Length' that stores the number of characters in the 'Name' column.

In [24]:
# [Write your code here]

## 13.  Apply and Lambda
**Theory:** `.apply()` lets you apply a custom function to a row or column. Combined with `lambda` (anonymous functions), it becomes a highly flexible tool.

In [25]:
# Create a salary bracket using apply and lambda
# Anyone > 80000 is High, else Medium
df_clean['Salary_Bracket'] = df_clean['Salary'].apply(lambda x: 'High' if x > 80000 else 'Medium')

display(df_clean[['Name', 'Salary', 'Salary_Bracket']])

   Name  Salary Salary_Bracket
0   Sam   75000         Medium
1  Nina   90000           High
2   Leo   82000           High
3   Mia   60000         Medium
4   Jay   95000           High
5   Zoe   65000         Medium
6   Tom   78000         Medium
7   Sam   75000         Medium

**🛠️ Practice Task 12:**
Use `lambda` and `apply` to add a 'Bonus' column which calculates 10% of the employee's 'Salary'.

In [26]:
# [Write your code here]

## 14.  Groupby
**Theory:** Grouping involves splitting the data into groups, applying a function (like mean, sum, count), and combining the results. It's the core of descriptive data analytics!

In [27]:
# Average salary per department
avg_salary = df_clean.groupby('Department')['Salary'].mean().reset_index()
print("--- Average Salary by Department ---")
display(avg_salary)

# Multiple aggregations at once
dept_stats = df_clean.groupby('Department').agg(
    Emp_Count=('Emp_ID', 'count'),
    Max_Exp=('Experience_Years', 'max'),
    Min_Salary=('Salary', 'min')
).reset_index()

print("\n--- Comprehensive Department Stats ---")
display(dept_stats)

--- Average Salary by Department ---

    Department   Salary
0         Data  77500.0
1  Engineering  92500.0
2           HR  60000.0
3    Marketing  65000.0

--- Comprehensive Department Stats ---

    Department  Emp_Count  Max_Exp  Min_Salary
0         Data          4        3       75000
1  Engineering          2        6       90000
2           HR          1        1       60000
3    Marketing          1        2       65000

**🛠️ Practice Task 13:**
Find the maximum salary in each 'Salary_Bracket' using `groupby`.

In [28]:
# [Write your code here]

## 15.  Merge and Concat
**Theory:**
- `concat`: Stacks DataFrames vertically (row-wise) or horizontally (column-wise).
- `merge`: Performs SQL-like joins mapping rows from two DataFrames based on common columns.

In [29]:
# --- Concat Example (Vertical Stacking) ---
new_emps = pd.DataFrame({
    'Emp_ID': [109, 110], 
    'Name': ['Umar', 'Sara'], 
    'Department': ['HR', 'Data']
})

# Keep subset of columns for simplicity
df_concat = pd.concat([df_clean[['Emp_ID', 'Name', 'Department']], new_emps], ignore_index=True)
print("--- CONCATENATED ---")
display(df_concat.tail(4))

# --- Merge Example (Left Join) ---
bonus_data = pd.DataFrame({
    'Emp_ID': [101, 103, 109], 
    'Bonus_Amount': [5000, 4000, 2000]
})

df_merged = pd.merge(df_concat, bonus_data, on='Emp_ID', how='left')
print("\n--- MERGED (Left Join) ---")
display(df_merged.head(4))
display(df_merged.tail(2))

--- CONCATENATED ---

   Emp_ID  Name Department
6     107   Tom       Data
7     108   Sam       Data
8     109  Umar         HR
9     110  Sara       Data

--- MERGED (Left Join) ---

   Emp_ID  Name   Department  Bonus_Amount
0     101   Sam         Data        5000.0
1     102  Nina  Engineering           NaN
2     103   Leo         Data        4000.0
3     104   Mia           HR           NaN

   Emp_ID  Name Department  Bonus_Amount
8     109  Umar         HR        2000.0
9     110  Sara       Data           NaN

**🛠️ Practice Task 14:**
Perform an 'inner' merge between `df_concat` and `bonus_data`. How many rows are returned?

In [30]:
# [Write your code here]

## 16.  value_counts, unique, and nunique
**Theory:**
- `value_counts()`: Returns the frequency of unique values.
- `unique()`: Returns an array of the unique values.
- `nunique()`: Returns the number of unique values.

In [31]:
print("Unique Departments List:", df_clean['Department'].unique())
print("Total number of Unique Departments:", df_clean['Department'].nunique())

print("\nDepartment Frequency Breakdown:")
display(df_clean['Department'].value_counts())

Unique Departments List: ['Data' 'Engineering' 'HR' 'Marketing']
Total number of Unique Departments: 4

Department Frequency Breakdown:

Department
Data           4
Engineering    2
HR             1
Marketing      1
Name: count, dtype: int64

**🛠️ Practice Task 15:**
Find the frequency of each 'Salary_Bracket' in `df_clean`.

In [32]:
# [Write your code here]

## 17.  Date-Time Operations
**Theory:** Real-world data depends heavily on time. Need to convert date strings to datetime objects using `pd.to_datetime()` to manipulate them properly.

In [33]:
# Convert string to datetime object
df_clean['Joining_Date'] = pd.to_datetime(df_clean['Joining_Date'])
print("Data type is now:", df_clean['Joining_Date'].dtype)

# Extracting specific date components
df_clean['Join_Year'] = df_clean['Joining_Date'].dt.year
df_clean['Join_Month'] = df_clean['Joining_Date'].dt.month_name()

display(df_clean[['Name', 'Joining_Date', 'Join_Year', 'Join_Month']])

Data type is now: datetime64[ns]

   Name Joining_Date  Join_Year Join_Month
0   Sam   2021-05-10       2021        May
1  Nina   2019-03-15       2019      March
2   Leo   2020-08-20       2020     August
3   Mia   2023-01-10       2023    January
4   Jay   2018-11-05       2018   November
5   Zoe   2022-07-01       2022       July
6   Tom   2020-12-01       2020   December
7   Sam   2021-05-10       2021        May

**🛠️ Practice Task 16:**
Extract the `day` from the 'Joining_Date' column and save it inside a new column called 'Join_Day'.

In [34]:
# [Write your code here]

## 18.  Mini Project: App Store Dataset Analysis
**Task Scenario:** You have scraped a small dataset of mobile applications. You need to clean it and answer specific business questions.

In [35]:
# 1. Load Dummy Dataset
app_data = {
    'App_Name': ['FitnessX', 'GameZ', 'FinancePro', 'StudyMate', 'GameZ', 'Health+', 'CryptoTrack'],
    'Category': ['Health', 'Gaming', 'Finance', 'Education', 'Gaming', 'Health', 'Finance'],
    'Rating': [4.5, np.nan, 4.8, 4.2, np.nan, 4.6, np.nan],
    'Downloads': ['10K', '500K', '50K', '20K', '500K', '100K', '5K'],
    'Price': ['$0.00', '$1.99', '$4.99', '$0.00', '$1.99', '$0.00', '$9.99']
}
apps = pd.DataFrame(app_data)
print("--- Original Raw Data ---")
display(apps)

# 2. Drop duplicates
apps = apps.drop_duplicates()

# 3. Handle Missing Ratings (Fill with average of available ratings)
avg_rating = apps['Rating'].mean()
apps['Rating'] = apps['Rating'].fillna(avg_rating).round(1)

# 4. Clean String Columns ('Downloads' to integer, 'Price' to float)
# Remove 'K' and multiply by 1000
apps['Downloads'] = apps['Downloads'].str.replace('K', '').astype(float) * 1000

# Remove '$' and convert to float
apps['Price'] = apps['Price'].str.replace('$', '').astype(float)

# 5. Question: Which category has the highest average downloads?
top_category = apps.groupby('Category')['Downloads'].mean().sort_values(ascending=False).head(1).reset_index()
print("\n--- Category with Highest Avg Downloads ---")
display(top_category)

# 6. Question: Add a column 'App_Type' -> 'Free' if Price == 0 else 'Paid'
apps['App_Type'] = apps['Price'].apply(lambda x: 'Free' if x == 0 else 'Paid')

print("\n--- Final Cleaned Data ---")
display(apps)

--- Original Raw Data ---

      App_Name   Category  Rating Downloads  Price
0     FitnessX     Health     4.5       10K  $0.00
1        GameZ     Gaming     NaN      500K  $1.99
2   FinancePro    Finance     4.8       50K  $4.99
3    StudyMate  Education     4.2       20K  $0.00
4        GameZ     Gaming     NaN      500K  $1.99
5      Health+     Health     4.6      100K  $0.00
6  CryptoTrack    Finance     NaN        5K  $9.99

--- Category with Highest Avg Downloads ---

  Category  Downloads
0   Gaming   500000.0

--- Final Cleaned Data ---

      App_Name   Category  Rating  Downloads  Price App_Type
0     FitnessX     Health     4.5    10000.0   0.00     Free
1        GameZ     Gaming     4.5   500000.0   1.99     Paid
2   FinancePro    Finance     4.8    50000.0   4.99     Paid
3    StudyMate  Education     4.2    20000.0   0.00     Free
5      Health+     Health     4.6   100000.0   0.00     Free
6  CryptoTrack    Finance     4.5     5000.0   9.99     Paid

**Final Task:**
Export the cleaned `apps` dataset to a CSV file named `cleaned_app_store_data.csv`.

------
**Congratulations! You have completed the Pandas Crash Course for Placements.** 🎉
Keep practicing, and good luck with your interviews!

In [36]:
# Write the export code here!