In [119]:
import pandas as pd

In [120]:
data = [1,2,3,4,5]
pd.Series(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [121]:
data = [1,2,3,4,5]

my_index = ['a','b','c','d','e']
pd.Series(data, index=my_index)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [122]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## To change the column name we have keyword `column` and to change the row name we should use the keyword `index`

In [123]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]] , columns= ['c1','c2','c3'], index=['r1','r2','r3'])
print(df)

    c1  c2  c3
r1   1   2   3
r2   4   5   6
r3   7   8   9

## In youtube videos or miniprojects we see excel or csv files but in real world large dataset they dont use csv or excel etc 
### They use `Parquet file` or `feather file`

#### These are highly optimised for large datasets like if the csv file is going to take 1GB for a data excel will take 1.2-1.3GB but these two Parquet file annd feather file take only 200-300 MB

In [124]:
#importing and Reading the dataset 

obesity_data = pd.read_csv('obesity_prediction.csv')

In [125]:
#Displays First 5 rows

obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [126]:
# u can change this by writing the number inside the brakets() how many number o rows u want

obesity_data.head(11)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight
10,Male,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I

In [127]:
#Displays last 5 rows

obesity_data.tail()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [128]:
# u can change this by writing the number inside the brakets() how many number o rows u want

obesity_data.tail(10)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2101,Female,25.722004,1.628470,107.218949,yes,yes,3.0,3.0,Sometimes,no,2.487070,no,0.067329,0.455823,Sometimes,Public_Transportation,Obesity_Type_III
2102,Female,25.765628,1.627839,108.107360,yes,yes,3.0,3.0,Sometimes,no,2.320068,no,0.045246,0.413106,Sometimes,Public_Transportation,Obesity_Type_III
2103,Female,21.016849,1.724268,133.033523,yes,yes,3.0,3.0,Sometimes,no,1.650612,no,1.537639,0.912457,Sometimes,Public_Transportation,Obesity_Type_III
2104,Female,21.682367,1.732383,133.043941,yes,yes,3.0,3.0,Sometimes,no,1.610768,no,1.510398,0.931455,Sometimes,Public_Transportation,Obesity_Type_III
2105,Female,21.285965,1.726920,131.335786,yes,yes,3.0,3.0,Sometimes,no,1.796267,no,1.728332,0.897924,Sometimes,Public_Transportation,Obesity_Type_III
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

## Now there is a high chance that the first 5 or 10 rows or last 5 or 10 rows dont show us the actual thing cz may be it is sorted or some other thing

### so we use a method called `sample`

## tO CREATE a subset of the dataset which can reperent the dataset properly

In [129]:
# default only one value 

obesity_data.sample()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
1288,Female,22.836315,1.604893,82.0,yes,yes,1.00876,1.0,Sometimes,no,2.0,no,0.0,0.585912,Sometimes,Public_Transportation,Obesity_Type_I

In [130]:
# we can give the number of sample values we want as well, THIS GIVE A DIFFERENT OUTPUT WITH EVER RUN

obesity_data.sample(10)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
1498,Female,18.000000,1.668555,85.607466,yes,yes,2.081238,3.000000,Sometimes,no,1.183630,no,1.171770,0.000000,no,Public_Transportation,Obesity_Type_I
318,Female,25.000000,1.560000,45.000000,no,yes,2.000000,3.000000,Sometimes,no,1.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
1114,Male,33.009285,1.741192,84.773349,yes,yes,2.000000,3.000000,Sometimes,no,2.035954,no,1.210736,0.000000,no,Automobile,Overweight_Level_II
498,Female,25.196214,1.686306,104.572712,yes,yes,3.000000,3.000000,Sometimes,no,1.152736,no,0.319156,1.000000,Sometimes,Public_Transportation,Obesity_Type_III
931,Female,21.538225,1.610327,67.999778,yes,yes,1.887951,3.728377,no,no,2.682107,no,1.123931,0.492528,Sometimes,Public_Transportation,Overweight_Level_I
733,Male,18.000000,1.707259,50.664459,yes,yes,1.786841,3.000000,Sometimes,no,1.546856,no,0.512094,1.608265,Sometimes,Public_Transportation,Insufficient_Weight
1697,Male,23.327836,1.754439,119.441207,yes,yes,1.893428,3.000000,Sometimes,no,2.000000,no,1.917383,0.936480,Sometimes,Public_Transportation,Obesity_Type_II
2072,Female,18.423482,1.735461,126.798173,yes,yes,3.000000,3.000000,Sometimes,no,2.386390,no,1.544632,0.900067,Sometimes,Public_Transportation,Obesity_Type_III
1518,Male,30.421596,1.819296,122.137917,yes,yes,2.000000,3.000000,Sometimes,no,1.984323,no,0.793262,0.000000,Sometimes,Public_Transportation,Obesity_Type_II
1364,Male,29.000000,1.666710,89.048151,yes,yes,1.897796,3.000000,Sometimes,no,1.193039,no,0.011519,0.000000,Sometimes,Automobile,Obesity_Type_I

In [131]:
# Giving the random state parameter will stop that new generation on every run, it will give the same output for that random state no matter how many times u run it

obesity_data.sample(10, random_state=29)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
631,Female,19.272573,1.713670,50.000000,no,yes,1.005578,4.000000,Frequently,no,1.000000,no,1.683957,0.704978,Sometimes,Public_Transportation,Insufficient_Weight
1216,Female,42.316070,1.583943,81.936398,yes,yes,2.490507,2.974204,Sometimes,no,1.846754,no,0.000000,0.000000,no,Automobile,Obesity_Type_I
1321,Female,23.000000,1.608469,82.954796,yes,yes,2.150054,2.988539,Sometimes,no,2.768325,no,2.085150,0.000000,no,Public_Transportation,Obesity_Type_I
1844,Female,26.000000,1.618573,104.928643,yes,yes,3.000000,3.000000,Sometimes,no,1.698767,no,0.000000,0.543960,Sometimes,Public_Transportation,Obesity_Type_III
820,Female,32.997118,1.672446,74.812707,yes,yes,2.948425,1.198643,Sometimes,no,1.000000,no,0.000000,0.173796,Sometimes,Automobile,Overweight_Level_I
2026,Female,21.838323,1.758959,137.792990,yes,yes,3.000000,3.000000,Sometimes,no,2.640539,no,1.879818,0.885993,Sometimes,Public_Transportation,Obesity_Type_III
692,Male,18.000000,1.767058,51.132809,yes,yes,2.708965,3.000000,Sometimes,no,1.873004,no,1.217180,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
454,Female,20.000000,1.680000,68.000000,no,yes,3.000000,1.000000,Sometimes,no,1.000000,no,1.000000,0.000000,no,Public_Transportation,Normal_Weight
875,Female,16.865984,1.644053,67.439589,yes,yes,1.314150,1.068196,Sometimes,no,1.364957,yes,0.000000,0.057926,no,Public_Transportation,Overweight_Level_I
1522,Male,28.363149,1.793476,112.725005,yes,yes,1.991240,3.000000,Sometimes,no,2.000000,no,0.000000,0.292956,Sometimes,Public_Transportation,Obesity_Type_II

# To just see what columns we have in the dataset we have a method called `columns`

In [132]:
list(obesity_data.columns

_IncompleteInputError: incomplete input (4070405571.py, line 1)

In [ ]:
# to see how many rows we have and with what index 

obesity_data.index

RangeIndex(start=0, stop=2111, step=1)

In [ ]:
# this gives both number of rows and number of columns 
obesity_data.shape

(2111, 17)

In [ ]:
# To get the number of cells 

obesity_data.size

35887

In [ ]:
# to get the basic aggrigation values

obesity_data.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [ ]:
# to get more information about the data

obesity_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          2111 non-null   object
 1   Age             2111 non-null   float64
 2   Height          2111 non-null   float64
 3   Weight          2111 non-null   float64
 4   family_history  2111 non-null   object
 5   FAVC            2111 non-null   object
 6   FCVC            2111 non-null   float64
 7   NCP             2111 non-null   float64
 8   CAEC            2111 non-null   object
 9   SMOKE           2111 non-null   object
 10  CH2O            2111 non-null   float64
 11  SCC             2111 non-null   object
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2111 non-null   object
 15  MTRANS          2111 non-null   object
 16  Obesity         2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

## `loc` - Accessing rows or group of rows using `labels`

In [ ]:
obesity_data.loc[0, 'Age']     # This is accessing the AGE of the 0th row

np.float64(21.0)

In [ ]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [ ]:
# we can also do this accessing for multiple values 

obesity_data.loc[0:5,'Age']     # both 0 and 5 is ncluded so it is inclusive

0    21.0
1    21.0
2    23.0
3    27.0
4    22.0
5    29.0
Name: Age, dtype: float64

In [ ]:
# we can also access multiple columns as well and in the order we want

obesity_data.loc[0:5,['Age','CALC','Weight']]

    Age        CALC  Weight
0  21.0          no    64.0
1  21.0   Sometimes    56.0
2  23.0  Frequently    77.0
3  27.0  Frequently    87.0
4  22.0   Sometimes    89.8
5  29.0   Sometimes    53.0

In [ ]:
# we can do this like a list of specificc values as well 

obesity_data.loc[[0,3,5],['Age','CALC','Weight']]

    Age        CALC  Weight
0  21.0          no    64.0
3  27.0  Frequently    87.0
5  29.0   Sometimes    53.0

In [ ]:
# we can also do this slicing in column name as well

obesity_data.loc[0:5,'Age':'CALC']

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC
0,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no
1,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes
2,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently
3,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently
4,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes
5,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes

In [ ]:
# FOR ALL THE ROWS

obesity_data.loc[:,'Age']

0       21.000000
1       21.000000
2       23.000000
3       27.000000
4       22.000000
          ...
2106    20.976842
2107    21.982942
2108    22.524036
2109    24.361936
2110    23.664709
Name: Age, Length: 2111, dtype: float64

## `iloc` - Accessing rows or group of rows using `index`

In [ ]:
obesity_data.iloc[0,5]   # In this tha last value is not inclusive

'no'

In [ ]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [ ]:
obesity_data.iloc[0:5,0:10]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no

In [ ]:
obesity_data.iloc[[10,20,30],[1,3,5]]

     Age  Weight FAVC
10  26.0   105.0  yes
20  22.0    80.0   no
30  29.0    83.0  yes

## For single value access at is more  efficient

In [ ]:
obesity_data.at[0,'Age']

np.float64(21.0)

In [ ]:
obesity_data.iat[2,1]   # 3rd row 1st column

np.float64(23.0)

## In loc and iloc w can only pass one value and it will be completly fine but for at and iat we should pass both the values

#

### loc iloc at iat and others focus on rows for columns its direct

In [ ]:
obesity_data['Age']    # shows all the values of the given column

0       21.000000
1       21.000000
2       23.000000
3       27.000000
4       22.000000
          ...
2106    20.976842
2107    21.982942
2108    22.524036
2109    24.361936
2110    23.664709
Name: Age, Length: 2111, dtype: float64

In [ ]:
obesity_data[['Age', 'Gender']]   # works for multiple columns as well

            Age  Gender
0     21.000000  Female
1     21.000000  Female
2     23.000000    Male
3     27.000000    Male
4     22.000000    Male
...         ...     ...
2106  20.976842  Female
2107  21.982942  Female
2108  22.524036  Female
2109  24.361936  Female
2110  23.664709  Female

[2111 rows x 2 columns]

for `loc` , `iloc` , `at` , `iat` we use `[]` and when we use conditions like `&` , `|` we should use `()` to the filter conditions before the operatator

In [ ]:
obesity_data.head(20)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight
10,Male,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I
11,Female,21.0,1.72,80.0,yes,yes,2.0,3.0,Frequently,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Overweight_Level_II
12,Male,22.0,1.65,56.0,no,no,3.0,3.0,Sometimes,no,3.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight
13,Male,41.0,1.80,99.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Automobile,Obesity_Type_I
14,Male,23.0,1.77,60.0,yes,yes,3.0,1.0,Sometimes,no,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
15,Female,22.0,1.70,66.0,yes,no,3.0,3.0,Always,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
16,Male,27.0,1.93,102.0,yes,yes,2.0,1.0,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
17,Female,29.0,1.53,78.0,no,yes,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I
18,Female,30.0,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0,0.0,no,Automobile,Overweight_Level_II
19,Female,23.0,1.65,70.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_I

In [ ]:
# Filter conditions

# obesity_data.loc[obesity_data['Height'] > 1.7 & obesity_data['Weight'] < 60 ]    # This will give error cz we dint use the ()  braket

obesity_data.loc[ ( obesity_data['Height'] > 1.7 ) & ( obesity_data['Weight'] < 60 ) & (obesity_data['Obesity']== 'Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
115,Female,17.0,1.75,57.0,yes,yes,3.0,3.0,Frequently,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
301,Male,18.0,1.72,55.0,no,yes,2.0,4.0,Sometimes,no,2.0,no,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
331,Male,17.0,1.74,56.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,no,Public_Transportation,Normal_Weight
422,Male,19.0,1.75,58.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Sometimes,Bike,Normal_Weight

In [ ]:
obesity_data.loc[ ( obesity_data['Height'] > 1.7 ) & ( obesity_data['Weight'] < 60 ) | (obesity_data['Obesity']== 'Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.000000,1.620000,64.000000,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.000000,3.000000,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
5,Male,29.000000,1.620000,53.000000,no,yes,2.000000,3.000000,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Automobile,Normal_Weight
6,Female,23.000000,1.500000,55.000000,yes,yes,3.000000,3.000000,Sometimes,no,2.000000,no,1.000000,0.000000,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,Male,18.000000,1.708107,51.314659,yes,yes,1.303878,3.000000,Sometimes,no,1.755497,no,0.062932,1.672532,Sometimes,Public_Transportation,Insufficient_Weight
735,Male,18.000000,1.739344,50.951444,yes,yes,1.889883,3.000000,Sometimes,no,1.959531,no,0.520407,1.151166,Sometimes,Public_Transportation,Insufficient_Weight
742,Male,18.000000,1.719827,52.289828,yes,yes,1.202075,3.000000,Sometimes,no,1.927976,no,0.023574,1.747256,Sometimes,Public_Transportation,Insufficient_Weight
743,Male,18.381382,1.722547,53.783977,yes,yes,2.000000,3.131032,Sometimes,no,2.072194,no,1.487987,2.000000,Sometimes,Public_Transportation,Insufficient_Weight
744,Male,18.000000,1.738702,50.248677,yes,yes,1.871213,3.000000,Sometimes,no,1.283738,no,0.684879,1.487223,Sometimes,Public_Transportation,Insufficient_Weight

## but we dont need to write loc specifically

In [ ]:
obesity_data[ ( obesity_data['Height'] > 1.7 ) & ( obesity_data['Weight'] < 60 ) & (obesity_data['Obesity']== 'Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
115,Female,17.0,1.75,57.0,yes,yes,3.0,3.0,Frequently,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
301,Male,18.0,1.72,55.0,no,yes,2.0,4.0,Sometimes,no,2.0,no,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
331,Male,17.0,1.74,56.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,no,Public_Transportation,Normal_Weight
422,Male,19.0,1.75,58.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Sometimes,Bike,Normal_Weight

In [ ]:
obesity_data[obesity_data['Obesity'].str.startswith('Normal')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,Male,25.0,1.66,68.0,no,yes,2.0,3.0,Sometimes,yes,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
493,Male,20.0,1.80,65.0,no,yes,2.0,3.0,Frequently,no,1.0,no,2.0,0.0,Sometimes,Motorbike,Normal_Weight
494,Female,18.0,1.67,66.0,no,yes,3.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
495,Male,19.0,1.80,60.0,yes,yes,3.0,1.0,Always,no,1.0,yes,0.0,0.0,no,Motorbike,Normal_Weight
497,Male,20.0,1.56,45.0,no,no,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

In [ ]:
obesity_data[obesity_data['Obesity'].str.startswith('Weight')]      # For no values this onl returns the empty table with column name

Empty DataFrame
Columns: [Gender, Age, Height, Weight, family_history, FAVC, FCVC, NCP, CAEC, SMOKE, CH2O, SCC, FAF, TUE, CALC, MTRANS, Obesity]
Index: []

# To update the data in the dataframe

#

# If we dont use `loc` or `iloc` the entire column will get updated

In [ ]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [ ]:
obesity_data.loc[0,'Age']= 23          # so the first row's age has now become 23

In [ ]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,"(0, Age)"
0,Female,23.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,23
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,23
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,23
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,23
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,23

In [ ]:
obesity_data.loc[ :2 , 'SMOKE'] = 'may be'             # the range is inclusive

In [ ]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,may be,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [ ]:
obesity_data.iloc[ 1, 4 ] = ' I dont know '

In [ ]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,I dont know,no,3.0,3.0,Sometimes,may be,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [ ]:
obesity_data.iloc[3:4, 9] = 'Doesnot matter'

In [ ]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,I dont know,no,3.0,3.0,Sometimes,may be,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,may be,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,Doesnot matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

# To perform transforrmation operations : use use `.apply` funtion

In [133]:
def Add_five_years_to_age(x):
    return x+5

obesity_data['Age'].apply(Add_five_years_to_age)

obesity_data['Age']     # if we dont write this line and stoop till above itself it shows the update ages, but if we write this line and exicute then it shows the orginal ages

# so to make the permanet change we should save the changes in the original one

0       21.000000
1       21.000000
2       23.000000
3       27.000000
4       22.000000
          ...
2106    20.976842
2107    21.982942
2108    22.524036
2109    24.361936
2110    23.664709
Name: Age, Length: 2111, dtype: float64

In [134]:
# like this:

obesity_data['Age'] = obesity_data['Age'].apply(Add_five_years_to_age)

obesity_data['Age']       # not it shows the updated values

0       26.000000
1       26.000000
2       28.000000
3       32.000000
4       27.000000
          ...
2106    25.976842
2107    26.982942
2108    27.524036
2109    29.361936
2110    28.664709
Name: Age, Length: 2111, dtype: float64

## So when the transformation is simple inside of `.apply()` we can use a `lambda` function insted of the traditional approach

In [135]:
obesity_data['Age'] = obesity_data['Age'].apply(lambda x:x-5)

obesity_data['Age']

0       21.000000
1       21.000000
2       23.000000
3       27.000000
4       22.000000
          ...
2106    20.976842
2107    21.982942
2108    22.524036
2109    24.361936
2110    23.664709
Name: Age, Length: 2111, dtype: float64

# To add a new column

In [137]:
obesity_data[ 'Age Category' ] = obesity_data['Age'].apply(lambda x:'Very Young' if x<24 else 'Not so young')

In [139]:
obesity_data.head(10)   # You can see a new column is added

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,Not so young
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,Very Young
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight,Not so young
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight,Very Young

# Inserting and deleting columns

In [149]:
obesity_data.insert( 4, 'BMI', obesity_data['Weight'] /obesity_data['Height'] **2 )

In [150]:
obesity_data.head()

,Gender,Age,Height,Weight,BMI,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,21.0,1.62,64.0,24.386526,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,24.238227,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,1.80,77.0,23.765432,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.0,1.80,87.0,26.851852,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.0,1.78,89.8,28.342381,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

### To delete the column permanently from the DataFrame we have 2 ways:
* using inplace = True 
* usning the dataframe name

In [151]:
obesity_data.drop(columns='BMI')        # here u see that the column is dropped

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,Very Young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,Not so young
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,Very Young

In [152]:
obesity_data.head(1)  # but here u see that column is still there

,Gender,Age,Height,Weight,BMI,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,21.0,1.62,64.0,24.386526,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young

In [156]:
# to remove it permanently from the dataframe:

obesity_data.drop(columns='BMI', inplace=True)
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [162]:
#creating again to show the 2nd method cz now its permanently deleted

obesity_data.insert( 4, 'BMI', obesity_data['Weight'] /obesity_data['Height'] **2 )
obesity_data.head(0)

Empty DataFrame
Columns: [Gender, Age, Height, Weight, BMI, family_history, FAVC, FCVC, NCP, CAEC, SMOKE, CH2O, SCC, FAF, TUE, CALC, MTRANS, Obesity, Age Category]
Index: []

In [163]:
obesity_data = obesity_data.drop(columns='BMI')
obesity_data.head(0)

Empty DataFrame
Columns: [Gender, Age, Height, Weight, family_history, FAVC, FCVC, NCP, CAEC, SMOKE, CH2O, SCC, FAF, TUE, CALC, MTRANS, Obesity, Age Category]
Index: []

In [170]:
# We can also delete multiple columns

# lets create 2 new dummy columns 

obesity_data.insert(0,'Dummy1',0)  # all values zero
obesity_data.insert(0,'Dummy2',1)  # all values one

In [171]:
obesity_data.head(0) # 2 new dummy columns created

Empty DataFrame
Columns: [Dummy2, Dummy1, Gender, Age, Height, Weight, family_history, FAVC, FCVC, NCP, CAEC, SMOKE, CH2O, SCC, FAF, TUE, CALC, MTRANS, Obesity, Age Category]
Index: []

In [172]:
obesity_data.drop(columns=['Dummy1','Dummy2'],inplace=True)

In [173]:
obesity_data.head(0)  # 2 new dummy columns deleted

Empty DataFrame
Columns: [Gender, Age, Height, Weight, family_history, FAVC, FCVC, NCP, CAEC, SMOKE, CH2O, SCC, FAF, TUE, CALC, MTRANS, Obesity, Age Category]
Index: []

# To delete the column with `del` keyword

In [174]:
del obesity_data['CAEC']

In [177]:
obesity_data.head(0)

Empty DataFrame
Columns: [Gender, Age, Height, Weight, family_history, FAVC, FCVC, NCP, SMOKE, CH2O, SCC, FAF, TUE, CALC, MTRANS, Obesity, Age Category]
Index: []

In [ ]:
obesity_data.rename(columns={'Age Category' : 'Age group'})    # renamed to age group but not permanently

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age group
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,Very Young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,Not so young
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,Very Young

In [ ]:
obesity_data.head(0)       # see its still age category so we will use inplace = True

Empty DataFrame
Columns: [Gender, Age, Height, Weight, family_history, FAVC, FCVC, NCP, SMOKE, CH2O, SCC, FAF, TUE, CALC, MTRANS, Obesity, Age Category]
Index: []

In [181]:
obesity_data.rename(columns={'Age Category' : 'Age group'},inplace=True)

In [182]:
obesity_data.head(0)

Empty DataFrame
Columns: [Gender, Age, Height, Weight, family_history, FAVC, FCVC, NCP, SMOKE, CH2O, SCC, FAF, TUE, CALC, MTRANS, Obesity, Age group]
Index: []

# Merging using joins

* Inner
* Outer
* Left
* Right

In [186]:
df1 = pd.DataFrame({

    'id': [1,2,3,4],
    'names': ['Zain', 'Ali', 'Ankit', 'Juhi']
})

df2 = pd.DataFrame({

    'id': [3,4,5,6],
    'Course': ['ML', 'DL', 'Pandas', 'Python']
})

In [194]:
print(df1)
print('---------------\n---------------')
print(df2)

   id  names
0   1   Zain
1   2    Ali
2   3  Ankit
3   4   Juhi
---------------
---------------
   id  Course
0   3      ML
1   4      DL
2   5  Pandas
3   6  Python

In [ ]:
inner_result = pd.merge(df1,df2,how='inner',on='id')

inner_result   # only common columns

   id  names Course
0   3  Ankit     ML
1   4   Juhi     DL

In [ ]:
outer_result = pd.merge(df1,df2,how='outer',on='id')

outer_result   # all the columns

   id  names  Course
0   1   Zain     NaN
1   2    Ali     NaN
2   3  Ankit      ML
3   4   Juhi      DL
4   5    NaN  Pandas
5   6    NaN  Python

In [ ]:
left_result = pd.merge(df1,df2,how='left',on='id')

left_result   # all columns from left and common columns from right

   id  names Course
0   1   Zain    NaN
1   2    Ali    NaN
2   3  Ankit     ML
3   4   Juhi     DL

In [ ]:
right_result = pd.merge(df1,df2,how='right',on='id')

right_result   # all columns from right and common columns from left

   id  names  Course
0   3  Ankit      ML
1   4   Juhi      DL
2   5    NaN  Pandas
3   6    NaN  Python

# Concatination

In [ ]:
df3 = pd.DataFrame({

    'id': [1,2,3,4],
    'names': ['Zain', 'Ali', 'Ankit', 'Juhi']
})

df4 = pd.DataFrame({

    'id': [3,4,5,6],
    'Course': ['ML', 'DL', 'Pandas', 'Python']
})

In [201]:
print(df3)
print('---------------\n---------------')
print(df4)

   id  names
0   1   Zain
1   2    Ali
2   3  Ankit
3   4   Juhi
---------------
---------------
   id  Course
0   3      ML
1   4      DL
2   5  Pandas
3   6  Python

In [ ]:
result1 = pd.concat([df3,df4])
result1


# but as u cann see the index is not in correct order

   id  names  Course
0   1   Zain     NaN
1   2    Ali     NaN
2   3  Ankit     NaN
3   4   Juhi     NaN
0   3    NaN      ML
1   4    NaN      DL
2   5    NaN  Pandas
3   6    NaN  Python

In [ ]:
result2 = pd.concat([df3,df4], ignore_index=True)
result2

# now its proper but what if i want them side by side ?

   id  names  Course
0   1   Zain     NaN
1   2    Ali     NaN
2   3  Ankit     NaN
3   4   Juhi     NaN
4   3    NaN      ML
5   4    NaN      DL
6   5    NaN  Pandas
7   6    NaN  Python

In [211]:
result3 = pd.concat([df3,df4], axis=1, )
result3

# now what if i want to know which values are from which dataframe ?

   id  names  id  Course
0   1   Zain   3      ML
1   2    Ali   4      DL
2   3  Ankit   5  Pandas
3   4   Juhi   6  Python

In [214]:
result4 = pd.concat([df3,df4],keys=['df3', 'df4'])
result4

       id  names  Course
df3 0   1   Zain     NaN
    1   2    Ali     NaN
    2   3  Ankit     NaN
    3   4   Juhi     NaN
df4 0   3    NaN      ML
    1   4    NaN      DL
    2   5    NaN  Pandas
    3   6    NaN  Python

## Checking for null values

In [216]:
result4.isna()

          id  names  Course
df3 0  False  False    True
    1  False  False    True
    2  False  False    True
    3  False  False    True
df4 0  False   True   False
    1  False   True   False
    2  False   True   False
    3  False   True   False

In [217]:
result4.isna().sum()

id        0
names     4
Course    4
dtype: int64

In [223]:
obesity_data.isna().sum()

Gender            0
Age               0
Height            0
Weight            0
family_history    0
FAVC              0
FCVC              0
NCP               0
SMOKE             0
CH2O              0
SCC               0
FAF               0
TUE               0
CALC              0
MTRANS            0
Obesity           0
Age group         0
dtype: int64

# As our dataset has no null values we should put some null values to learn this topic

In [228]:
import numpy as np

In [229]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age group
0,Female,21,1.62,64.0,yes,no,2.0,3.0,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

### PUTTING NULL VALUES

In [252]:
# I will be putting this code cell multiple times this is just to create the null values again, nothing more

obesity_data.loc[0,'Age'] = np.nan
obesity_data.loc[0,'SMOKE'] = np.nan
obesity_data.loc[0,'family_history'] = np.nan

In [240]:
obesity_data.head()  # you can see many null values now

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age group
0,Female,NaN,1.62,64.0,NaN,no,2.0,3.0,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [241]:
obesity_data.fillna(0)  # now this really doesnot make any sense bcz age, family history and smoke, in all the columns it was inserted and it is not permanent as well

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age group
0,Female,0.000000,1.620000,64.000000,0,no,2.0,3.0,0,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,Very Young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,Not so young
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,Very Young

In [242]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age group
0,Female,NaN,1.62,64.0,NaN,no,2.0,3.0,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [274]:
obesity_data['Age']=obesity_data['Age'].fillna(20)

obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age group
0,Female,20.0,1.62,64.0,no,no,2.0,3.0,may be,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,25.5,1.80,87.0,no,no,3.0,3.0,may be,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,28.0,1.78,89.8,no,no,2.0,1.0,may be,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [253]:
# or lets say we can even use :

obesity_data['Age']=obesity_data['Age'].fillna(obesity_data['Age'].mean())

obesity_data.head()

C:\Users\mdzai\AppData\Local\Temp\ipykernel_28584\2488889090.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  obesity_data['Age']=obesity_data['Age'].fillna(obesity_data['Age'].mean())

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age group
0,Female,24.31417,1.62,64.0,NaN,no,2.0,3.0,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.00000,1.52,56.0,yes,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.00000,1.80,77.0,yes,no,2.0,3.0,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.00000,1.80,87.0,no,no,3.0,3.0,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.00000,1.78,89.8,no,no,2.0,1.0,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [273]:
# to fill the non numarical columns we can use a dictionary

obesity_data.fillna({'family_history' : 'no' , 'SMOKE' : 'may be'},inplace=True)

obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age group
0,Female,20.0,1.62,64.0,no,no,2.0,3.0,may be,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,25.5,1.80,87.0,no,no,3.0,3.0,may be,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,28.0,1.78,89.8,no,no,2.0,1.0,may be,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [ ]:
obesity_data.loc[0,'Age'] = np.nan
obesity_data.loc[0,'SMOKE'] = np.nan
obesity_data.loc[0,'family_history'] = np.nan

In [ ]:
obesity_data.fillna(obesity_data.interpolate())    # Nothing changed cz  the null values were in the first row, this works in not first rows only

C:\Users\mdzai\AppData\Local\Temp\ipykernel_28584\3317090513.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  obesity_data.fillna(obesity_data.interpolate())

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age group
0,Female,NaN,1.620000,64.000000,NaN,no,2.0,3.0,NaN,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,Very Young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,Very Young
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,Not so young
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,Very Young

In [275]:
obesity_data.loc[3,'Age'] = np.nan
obesity_data.loc[3,'SMOKE'] = np.nan
obesity_data.loc[3,'family_history'] = np.nan

In [276]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age group
0,Female,20.0,1.62,64.0,no,no,2.0,3.0,may be,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,NaN,1.80,87.0,NaN,no,3.0,3.0,NaN,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,28.0,1.78,89.8,no,no,2.0,1.0,may be,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [278]:
obesity_data.fillna(obesity_data.interpolate(), inplace=True)

obesity_data.head()

C:\Users\mdzai\AppData\Local\Temp\ipykernel_28584\913963944.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  obesity_data.fillna(obesity_data.interpolate(), inplace=True)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age group
0,Female,20.0,1.62,64.0,no,no,2.0,3.0,may be,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,25.5,1.80,87.0,NaN,no,3.0,3.0,NaN,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,28.0,1.78,89.8,no,no,2.0,1.0,may be,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

## To drop the null values

In [283]:
obesity_data.dropna(inplace=True)

obesity_data.head()  # you can see the 3rd rows is gone bcz it had a missing value

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age group
0,Female,20.0,1.62,64.0,no,no,2.0,3.0,may be,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
4,Male,28.0,1.78,89.8,no,no,2.0,1.0,may be,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,Not so young

# GroupBy function

In [290]:
obesity_data.groupby('Gender').count()

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age group
Gender,,,,,,,,,,,,,,,,
Female,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043
Male,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067,1067

In [291]:
obesity_data.groupby('Gender')['Height'].median()

Gender
Female    1.639524
Male      1.760000
Name: Height, dtype: float64

In [292]:
obesity_data.groupby('Gender')['Weight'].mean()

Gender
Female    82.302364
Male      90.773011
Name: Weight, dtype: float64

In [297]:
obesity_data.groupby('Gender')['Weight'].agg(['sum','mean'])

                 sum       mean
Gender
Female  85841.365833  82.302364
Male    96854.802872  90.773011