## Tasks 

1. Read the CSV into DataFrame

2. Show first 5 rows

3. Create a new column:

       Total_Sales = Price × Quantity

4. Find total sales of the entire dataset

5. Find the product with highest total sales    (Hint: same concept as idxmax())

6. Find all orders from Bangalore

7. Find total sales city-wise using groupby()   (This is the most important task.)

8. Find category-wise average price

9. Find the city with highest total sales

In [24]:
# 1. reading csv into DataFrame

import pandas as pd

df = pd.read_csv('sales.csv')

In [25]:
# 2. showing first 5 rows

df.head()

   Order_ID Product     Category  Price  Quantity       City
0      1001  Laptop  Electronics  55000         2  Bangalore
1      1002   Mouse  Electronics    800         5  Hyderabad
2      1003   Chair    Furniture   3500         3      Delhi
3      1004   Table    Furniture   7000         1     Mumbai
4      1005   Phone  Electronics  30000         4  Bangalore

In [26]:
# 3. Creating the new column Total_Sales

df['Total_Sales'] = df['Price'] * df['Quantity']

df

   Order_ID   Product     Category  Price  Quantity       City  Total_Sales
0      1001    Laptop  Electronics  55000         2  Bangalore       110000
1      1002     Mouse  Electronics    800         5  Hyderabad         4000
2      1003     Chair    Furniture   3500         3      Delhi        10500
3      1004     Table    Furniture   7000         1     Mumbai         7000
4      1005     Phone  Electronics  30000         4  Bangalore       120000
5      1006  Notebook   Stationery    100        10    Chennai         1000
6      1007       Pen   Stationery     20        50      Delhi         1000
7      1008   Monitor  Electronics  12000         2  Hyderabad        24000
8      1009      Sofa    Furniture  15000         1     Mumbai        15000
9      1010  Keyboard  Electronics   1500         3  Bangalore         4500

In [27]:
# 4. Find total sales of the entire dataset

df['Total_Sales'].agg(['sum'])

sum    297000
Name: Total_Sales, dtype: int64

In [5]:
# 5. Find the product with highest total sales

df.loc[df['Total_Sales'].idxmax(),'Product']

'Phone'

In [57]:
# 6. Find all orders from Bangalore
df.loc[df['City'] == 'Bangalore']

   Order_ID   Product     Category  Price  Quantity       City  Total_Sales
0      1001    Laptop  Electronics  55000         2  Bangalore       110000
4      1005     Phone  Electronics  30000         4  Bangalore       120000
9      1010  Keyboard  Electronics   1500         3  Bangalore         4500

In [42]:
# 7. Find total sales city-wise using groupby()   (This is the most important task.)

df.groupby('City')['Total_Sales'].sum()

City
Bangalore    234500
Chennai        1000
Delhi         11500
Hyderabad     28000
Mumbai        22000
Name: Total_Sales, dtype: int64

In [51]:
# 8. Find category-wise average price

df.groupby('Category')['Price'].mean()

Category
Electronics    19860.0
Furniture       8500.0
Stationery        60.0
Name: Price, dtype: float64

In [66]:
# 9. Find the city with highest total sales

city_sales = df.groupby('City')['Total_Sales'].sum()
city_sales.idxmax()

'Bangalore'