## Task Set 1
1. Read the CSV file into a DataFrame
2. Show first 5 rows
3. Show dataset info
4. Show statistical summary
5. Find student with highest Maths marks
6. Find average attendance
7. Show students with attendance > 90
8. Create a new column Average_Marks

`Formula:`
            `(Maths+Science+English)/3`


Average_Marks= (Maths+Science+English) / 3


9. Find topper based on average marks

In [11]:
# 1. Read the CSV file into a DataFrame
import pandas as pd

df = pd.read_csv('students.csv')

In [12]:
# 2. Show first 5 rows

df.head()

   Student_ID    Name  Maths  Science  English  Attendance
0         101   Ayaan     88       92       85          95
1         102    Sara     76       81       79          88
2         103   Rahul     90       87       91          96
3         104  Fatima     69       74       72          85
4         105   Arjun     95       89       94          98

In [13]:
# 3. Show dataset info

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  8 non-null      int64
 1   Name        8 non-null      object
 2   Maths       8 non-null      int64
 3   Science     8 non-null      int64
 4   English     8 non-null      int64
 5   Attendance  8 non-null      int64
dtypes: int64(5), object(1)
memory usage: 516.0+ bytes

In [14]:
# 4. Show statistical summary

df.describe()

       Student_ID      Maths    Science    English  Attendance
count     8.00000   8.000000   8.000000   8.000000    8.000000
mean    104.50000  82.500000  82.750000  83.250000   91.625000
std       2.44949   9.576758   9.003967   7.995534    5.578978
min     101.00000  69.000000  68.000000  72.000000   84.000000
25%     102.75000  74.750000  77.000000  78.000000   87.250000
50%     104.50000  85.000000  84.000000  82.500000   92.500000
75%     106.25000  89.250000  89.750000  90.250000   96.250000
max     108.00000  95.000000  93.000000  94.000000   98.000000

In [48]:
# 5. Find student with highest Maths marks

highest_maths_marks = df.loc[df['Maths'].idxmax(), 'Name']
highest_maths_marks

'Arjun'

In [ ]:
# 6. Find average attendance

avg_attendance = df['Attendance'].mean()
avg_attendance

np.float64(91.625)

In [32]:
# 7. Show students with attendance > 90

df['Name'][df['Attendance']>90]

0    Ayaan
2    Rahul
4    Arjun
7    Meera
Name: Name, dtype: object

In [56]:
# alternative approaches for the above:

df.loc[df['Attendance'] > 90, 'Name']    # using .loc

0    Ayaan
2    Rahul
4    Arjun
7    Meera
Name: Name, dtype: object

In [55]:
df[df['Attendance'] > 90]      # This gives the full rows, not just names.

   Student_ID   Name  Maths  Science  English  Attendance  Average_Marks
0         101  Ayaan     88       92       85          95      88.333333
2         103  Rahul     90       87       91          96      89.333333
4         105  Arjun     95       89       94          98      92.666667
7         108  Meera     89       93       90          97      90.666667

In [ ]:
# 8. Create a new column Average_Marks

df['Average_Marks'] = (df['Maths']+df['Science']+df['English'])/ 3
df

   Student_ID    Name  Maths  Science  English  Attendance  Average_Marks
0         101   Ayaan     88       92       85          95      88.333333
1         102    Sara     76       81       79          88      78.666667
2         103   Rahul     90       87       91          96      89.333333
3         104  Fatima     69       74       72          85      71.666667
4         105   Arjun     95       89       94          98      92.666667
5         106    Zoya     82       78       80          90      80.000000
6         107   Karan     71       68       75          84      71.333333
7         108   Meera     89       93       90          97      90.666667

In [50]:
# 9. Find topper based on average marks
topper = df.loc[df['Average_Marks'].idxmax(), 'Name']
topper

'Arjun'

In [51]:
# bonus :  if we want the details of the topper and not just the name then :

topper_details = df.loc[df['Average_Marks'].idxmax()]
topper_details

Student_ID             105
Name                 Arjun
Maths                   95
Science                 89
English                 94
Attendance              98
Average_Marks    92.666667
Name: 4, dtype: object